version: '3'
services:
  honeysense:
    build: .
    ports:
      - "8080:8080"
      - "2222:2222"
      - "3306:3306"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: always
